blog/urls.py
from django.urls import path
from blog.feeds import LatestEntriesFeed
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_view ,name='blog'),
    path('category/<str:cat_name>', blog_view ,name='category'),
    path('<str:post_id>', single_view ,name='single'),
    path('tag/<str:tag_name>', blog_view ,name='tag'),
    path('author/<str:author_username>', blog_view ,name='author'),
    path('search/', blog_search, name='search'),
    path("rss/feed/", LatestEntriesFeed(), name='rss'),

]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from homepage.views import *

app_name = 'homepage'

urlpatterns = [
    path('', index_view ,name='index'),
    path('about', about_view,name='about' ),
    path('contact', contact_view ,name='contact'),
    path('newsletter', newsletter_view ,name='newsletter'),
    path('news/<str:news_id>', single_news ,name='news'),
    path('news/category/<str:cat_name>', index_view ,name='category'),
    path('tag/<str:tag_name>', index_view ,name='tag'),
    path('author/<str:author>', index_view ,name='author'),
    path('search/', index_search, name='search'),

] 

itmeter/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from django.contrib.sitemaps.views import sitemap

from homepage.sitemaps import StaticViewSitemap,NewsSitemap
from blog.sitemaps import BlogSitemap

from debug_toolbar.toolbar import debug_toolbar_urls


sitemaps = {
    "static": StaticViewSitemap,
    "blog" : BlogSitemap,
    "blog" : NewsSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('accounts.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
    path('captcha/', include('captcha.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



urlpatterns +=  debug_toolbar_urls()

from django.contrib.auth import views as auth_views
urlpatterns += [
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
class Post(models.Model):
    image = models.ImageField(upload_to='blog/%Y/%m/%d/',default='blog/defaultPost.jpg')
    #author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    topic = models.ForeignKey('homepage.Topic', on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0) # default=0
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created_date',)
        #verbose_name = "پست"
        #verbose_name_plural = "پست ها"
    def __str__(self):
        return f'{self.title} - {self.id}'

    def snippets(self):
        return self.content[:100]
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'post_id':self.id})
    

class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    def __str__(self):
        return f'{self.name} - post : {self.post}'
    class Meta:
        ordering = ('-created_date',)

blog/forms.py
from django import forms
from blog.models import PostComment
from captcha.fields import CaptchaField


class PostCommentForm(forms.ModelForm):
    #captcha = CaptchaField()
    class Meta:
        model = PostComment
        fields =  ['post','name','email','subject' ,'message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Post,PostComment
from django.utils import timezone
from blog.forms import PostCommentForm
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
# Create your views here.
from django.contrib import messages



def blog_view(request,**kwargs):
#def blog_view(request,cat_name=None,author_username=None):
    posts = Post.objects.filter(status=1 , published_date__lte=timezone.now())
    if kwargs.get('cat_name') is not None:
    #if cat_name:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') is not None:
    #if author_username:
        posts = posts.filter(author__username =kwargs['author_username'])
    if kwargs.get('tag_name') is not None:
    #if tag_name:
        posts = posts.filter(tags__name=kwargs['tag_name'])
    posts = Paginator(posts,4)
 
    
    comments = PostComment.objects.filter(approved=True).order_by('-created_date')
    
    try:        
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts': posts, 'comments' : comments}
    return render(request, 'blog/blog.html', context=context)

def single_view(request, post_id):
    if request.method == 'POST':
        form = PostCommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS ,"Your Comment Submitted") 
        else:
            messages.add_message(request, messages.ERROR, "Your Comment did not Submitted!", {'form':form })

        
    
    current_post = get_object_or_404(Post,status=1, id = post_id)    
    current_post.counted_views += 1
    current_post.save()

    all_posts = Post.objects.all().order_by('published_date').filter(status=1, published_date__lte=timezone.now())
    current_index = list(all_posts).index(current_post)
    previous_post = all_posts[current_index - 1] if current_index > 0 else None
    next_post = all_posts[current_index + 1] if current_index < len(all_posts) - 1 else None
    comments = PostComment.objects.filter(post_id =current_post.id,approved=True)

    form = PostCommentForm()
    context = {
        'current_post': current_post,
        'previous_post': previous_post,
        'next_post': next_post,
        'comments' : comments,
        'form' : form,
    }
    if not current_post.login_require:        
        return render(request, 'blog/single.html', context)
    else:
        if not request.user.is_authenticated:         
            return HttpResponseRedirect(reverse('accounts:login'))
        else:
            return render(request, 'blog/single.html', context)
        

def blog_search(request):
    posts = Post.objects.filter(status=1 , published_date__lte=timezone.now())  
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains = s)    
    context = {'posts': posts}
    return render(request, 'blog/blog.html', context=context)

templates/blog/author.html
{% load static %}

<div class="custombox authorbox clearfix">
    <h4 class="small-title">About author</h4>
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
            <img src="{% static 'upload/author.jpg' %}" alt="" class="img-fluid rounded-circle">
        </div><!-- end col -->

        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <h4><a href="#">{{current_post.author.get_full_name}}</a></h4>
            <p>Quisque sed tristique felis. Lorem <a href="#">visit my website</a> amet, consectetur
                adipiscing elit. Phasellus quis mi auctor, tincidunt nisl eget, finibus odio. Duis
                tempus elit quis risus congue feugiat. Thanks for stop Tech Blog!</p>

            <div class="topsocial">
                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i
                        class="fa fa-facebook"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Youtube"><i
                        class="fa fa-youtube"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i
                        class="fa fa-pinterest"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i
                        class="fa fa-twitter"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i
                        class="fa fa-instagram"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="bottom" title="Website"><i
                        class="fa fa-link"></i></a>
            </div><!-- end social -->

        </div><!-- end col -->
    </div><!-- end row -->
</div><!-- end author-box -->

<hr class="invis1">

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load template_tag %}
{% block content %}

<div class="page-title lb single-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <h2><i class="fa fa-gears bg-orange"></i> Reviews <small class="hidden-xs-down hidden-sm-down">Explore in-depth reviews of the latest tech products and innovations.</small></h2>
            </div><!-- end col -->
            <div class="col-lg-4 col-md-4 col-sm-12 hidden-xs-down hidden-sm-down">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage:index' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Reviews</a></li>

                </ol>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end page-title -->

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <div class="sidebar">

                    <div class="widget">
                        <div class="banner-spot clearfix">
                            <div class="banner-img">
                                <img src="{% static 'images/banner-300-600.jpg' %}" alt="" class="img-fluid">
                            </div><!-- end banner-img -->
                        </div><!-- end banner -->
                    </div><!-- end widget -->

                    <!-- trend-videos -->

                    {% include 'blog/post-search.html' %}  

                    {% include 'blog/popular-posts.html' %}

                    <!-- recent-reviews -->

                    {% include 'blog/follow-us.html' %}

                    <div class="widget">
                        <div class="banner-spot clearfix">
                            <div class="banner-img">
                                <img src="{% static 'images/banner-1200-1200.jpg' %}" alt="" class="img-fluid">
                            </div><!-- end banner-img -->
                        </div><!-- end banner -->
                    </div><!-- end widget -->


                </div><!-- end sidebar -->
            </div><!-- end col -->

            <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                <div class="page-wrapper">
                    <div class="blog-grid-system">
                        
                        <div class="row">
                            {% for post in posts %}                            
                                <div class="col-md-6">
                                    <div class="blog-box">
                                        <div class="post-media">
                                            <a href="{% url 'blog:single' post_id=post.id %}" title="">
                                                <img src="{{ post.image.url }}" alt="" class="img-fluid">
                                                <div class="hovereffect">
                                                    <span></span>
                                                </div><!-- end hover -->
                                            </a>
                                        </div><!-- end media -->
                                        <div class="blog-meta big-meta">
                                            <span class="color-orange"><a href="#" title="">{{post.topic}}</a></span>
                                            <h4><a href="{% url 'blog:single' post_id=post.id %}" title="">{{post.title}}</a></h4>
                                            <p>{{post.content|truncate_w:38|safe}}</p>
                                            <small><a href="{% url 'blog:single' post_id=post.id %}" title="">{{post.published_date|date:'d D M Y'}}</a></small>
                                            <small><a href="{% url 'blog:author' author_username=post.author.username %}" title="">{{post.author.get_full_name}}</a></small>
                                            <small><a href="{% url 'blog:single' post_id=post.id %}" title=""><i class="fa fa-eye"></i> {{post.counted_views}} Views </a></small>
                                        </div><!-- end meta -->
                                    </div><!-- end blog-box -->
                                </div><!-- end col -->
                            {% endfor %}
                        </div><!-- end row -->
                        
                    </div><!-- end blog-grid-system -->
                </div><!-- end page-wrapper -->

                <hr class="invis3">

                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation">
                            <ul class="pagination justify-content-start">
                                {% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                Prev</a>
		                            </li>
								{% endif %}

								{% for i in posts.paginator.page_range %}
									{% if posts.number == i %}																			
		                        	    <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
									{% else %}
		                        	    <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
									{% endif %}
								{% endfor %}		                            
									
		                        {% if posts.has_next %}
									<li class="page-item">
		                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                Next</a>
		                            </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>
{% endblock %}

templates/blog/follow-us.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Follow Us</h2>

    <div class="row text-center">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
            <a href="#" class="social-button facebook-button">
                <i class="fa fa-facebook"></i>
                <p>27k</p>
            </a>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
            <a href="#" class="social-button twitter-button">
                <i class="fa fa-twitter"></i>
                <p>98k</p>
            </a>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
            <a href="#" class="social-button google-button">
                <i class="fa fa-google-plus"></i>
                <p>17k</p>
            </a>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
            <a href="#" class="social-button youtube-button">
                <i class="fa fa-youtube"></i>
                <p>22k</p>
            </a>
        </div>
    </div>
</div><!-- end widget -->

templates/blog/popular-posts.html
{% load static %}
{% load template_tag %}
{% load humanize %} 

<div class="widget">
    <h2 class="widget-title">Most Viewed Posts</h2>
    <div class="blog-list-widget">
        <div class="list-group">
            {% for post in posts %}
            <a href="{% url 'blog:single' post_id=post.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="w-100 justify-content-between">
                    <img src="{{ post.image.url }}" alt="" class="img-fluid float-left">
                    <h5 class="mb-1">{{post.title|truncate_w:6|safe}}</h5>
                    <small>{{post.published_date| naturaltime}}</small>
                </div>
            </a>
            {% endfor %}
        </div>
    </div><!-- end blog-list -->
</div><!-- end widget -->

templates/blog/post-search.html
{% load static %}
{% load template_tag %}
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/recent-reviews.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Recent Reviews</h2>
    <div class="blog-list-widget">
        <div class="list-group">
            {% for post in posts %}
                <a href="{% url 'blog:single' post_id=post.id %}"
                    class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="w-100 justify-content-between">
                        <img src="{% static 'upload/tech_blog_02.jpg' %}" alt=""
                            class="img-fluid float-left">
                        <h5 class="mb-1">{{post.tile}}</h5>
                        <span class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </span>
                    </div>
                </a>
            {% endfor %}            
        </div>
    </div><!-- end blog-list -->
</div><!-- end widget -->

templates/blog/same_post.html
{% load static %}

<div class="custombox clearfix">
    <h4 class="small-title">You may also like</h4>
    <div class="row">
        {% for post in posts %}
        <div class="col-lg-6">
            <div class="blog-box">
                <div class="post-media">
                    <a href="{% url 'blog:single' post_id=post.id %}" title="">
                        <img src="{% static 'upload/tech_menu_04.jpg' %}" alt="" class="img-fluid">
                        <div class="hovereffect">
                            <span class=""></span>
                        </div><!-- end hover -->
                    </a>
                </div><!-- end media -->
                <div class="blog-meta">
                    <h4><a href="{% url 'blog:single' post_id=post.id %}" title="">We are guests of ABC Design
                            Studio</a></h4>
                    <small><a href="blog-blog.html" title="">Trends</a></small>
                    <small><a href="blog-blog.html" title="">21 July, 2017</a></small>
                </div><!-- end meta -->
            </div><!-- end blog-box -->
        </div><!-- end col -->
        {% endfor %}
        
    </div><!-- end row -->
</div><!-- end custom-box -->

templates/blog/trend-videos.html
{% load static %}

<div class="widget">
    <h2 class="widget-title">Trend Videos</h2>
    <div class="trend-videos">
        {% for post in posts %}
            <div class="blog-box">
                <div class="post-media">
                    <a href="{% url 'blog:single' post_id=post.id %}" title="">
                        <img src="{% static 'upload/tech_video_01.jpg' %}" alt="" class="img-fluid">
                        <div class="hovereffect">
                            <span class="videohover"></span>
                        </div><!-- end hover -->
                    </a>
                </div><!-- end media -->
                <div class="blog-meta">
                    <h4><a href="{% url 'blog:single' post_id=post.id %}" title="">We prepared the best 10 laptop presentations for you</a></h4>
                </div><!-- end meta -->
            </div><!-- end blog-box -->
            <hr class="invis">
        {% endfor %}

    </div><!-- end videos -->
</div><!-- end widget -->